from dataAnalysis.main_module import *
import dataAnalysis.distributions_module as distribution
import dataAnalysis.linear_regression_module as linearRegression
import dataAnalysis.matrix_module as matrix